spring:
  ssl:
    bundle:
      jks:
        client:
          keystore:
            location: classpath:client-truststore.jks
            password: changeit
            type: JKS
          key:
            alias: clientkey
