spring:
  ssl:
    bundles:
      mybundle:
        key:
          store: classpath:keystore/my-keystore.jks
          password: changeit
        trust:
          store: classpath:keystore/my-truststore.jks
          password: changeit
